// <auto-generated />
using System;
using MaintenanceService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaintenanceService.Infrastructure.Migrations
{
    [DbContext(typeof(MaintenanceDbContext))]
    partial class MaintenanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MaintenanceService.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TicketEquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TicketEquipmentId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.CatalogActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("CatalogActivities");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.CatalogDiagnosis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("CatalogDiagnoses");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.DeviceReplacement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AsignadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EquipoEntranteCodigo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("EquipoEntranteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EquipoSalienteCodigo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("EquipoSalienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaReemplazo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EquipoEntranteId")
                        .IsUnique();

                    b.HasIndex("TicketId");

                    b.ToTable("DeviceReplacements");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("TicketEquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TicketEquipmentId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.StatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("StatusHistories");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.TicketEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastStatusChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastStatusChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observation")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TicketId", "EquipmentId")
                        .IsUnique();

                    b.ToTable("TicketEquipments");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.TicketEquipmentActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CatalogActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TicketEquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CatalogActivityId");

                    b.HasIndex("TicketEquipmentId", "CatalogActivityId")
                        .IsUnique();

                    b.ToTable("TicketEquipmentActivities");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.TicketEquipmentDiagnosis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CatalogDiagnosisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TicketEquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CatalogDiagnosisId");

                    b.HasIndex("TicketEquipmentId", "CatalogDiagnosisId")
                        .IsUnique();

                    b.ToTable("TicketEquipmentDiagnoses");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.TicketTechnician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityDescription")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observations")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("TechnicianUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TicketEquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TicketEquipmentId", "TechnicianUserId")
                        .IsUnique();

                    b.ToTable("TicketTechnicians");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.Activity", b =>
                {
                    b.HasOne("MaintenanceService.Domain.Entities.TicketEquipment", "TicketEquipment")
                        .WithMany("Activities")
                        .HasForeignKey("TicketEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TicketEquipment");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.DeviceReplacement", b =>
                {
                    b.HasOne("MaintenanceService.Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.Resource", b =>
                {
                    b.HasOne("MaintenanceService.Domain.Entities.TicketEquipment", "TicketEquipment")
                        .WithMany("Resources")
                        .HasForeignKey("TicketEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TicketEquipment");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.TicketEquipment", b =>
                {
                    b.HasOne("MaintenanceService.Domain.Entities.Ticket", "Ticket")
                        .WithMany("TicketEquipments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.TicketEquipmentActivity", b =>
                {
                    b.HasOne("MaintenanceService.Domain.Entities.CatalogActivity", "CatalogActivity")
                        .WithMany("TicketEquipmentActivities")
                        .HasForeignKey("CatalogActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaintenanceService.Domain.Entities.TicketEquipment", "TicketEquipment")
                        .WithMany("TicketEquipmentActivities")
                        .HasForeignKey("TicketEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogActivity");

                    b.Navigation("TicketEquipment");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.TicketEquipmentDiagnosis", b =>
                {
                    b.HasOne("MaintenanceService.Domain.Entities.CatalogDiagnosis", "CatalogDiagnosis")
                        .WithMany("TicketEquipmentDiagnoses")
                        .HasForeignKey("CatalogDiagnosisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaintenanceService.Domain.Entities.TicketEquipment", "TicketEquipment")
                        .WithMany("TicketEquipmentDiagnoses")
                        .HasForeignKey("TicketEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogDiagnosis");

                    b.Navigation("TicketEquipment");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.TicketTechnician", b =>
                {
                    b.HasOne("MaintenanceService.Domain.Entities.TicketEquipment", "TicketEquipment")
                        .WithMany("TicketTechnicians")
                        .HasForeignKey("TicketEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TicketEquipment");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.CatalogActivity", b =>
                {
                    b.Navigation("TicketEquipmentActivities");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.CatalogDiagnosis", b =>
                {
                    b.Navigation("TicketEquipmentDiagnoses");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("TicketEquipments");
                });

            modelBuilder.Entity("MaintenanceService.Domain.Entities.TicketEquipment", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Resources");

                    b.Navigation("TicketEquipmentActivities");

                    b.Navigation("TicketEquipmentDiagnoses");

                    b.Navigation("TicketTechnicians");
                });
#pragma warning restore 612, 618
        }
    }
}
